### ISSUE TITLE
Стабильный brokenEvent

### ISSUE THREAD

**Issue by Hoxxtonz** [cursedseal/VCoinX#104]
![Снимок999999999999999999](https://user-images.githubusercontent.com/49348038/55673188-1c5db300-58ad-11e9-8be9-2cc15cc0be10.PNG)
Происходит выборочно, с другими двумя аккаунтами проблем нет

**Comment by ghost** [comment]
такая же шляпа

**Comment by apepenkov** [comment]
упали сервера, у меня на всех так, и с мобилы

**Comment by Slivondiy** [comment]
У меня так же!

**Comment by Allespro** [comment]
Всё померло

**Comment by Xinulojahu** [comment]
Тоже самое на всех

**Comment by cbugerr** [comment]
у меня тоже так, уже минут 30, хотя с телефона работает все

**Comment by vsevollodm** [comment]
пздц

**Comment by SheyhSd** [comment]
ля какого черта?

**Comment by SheyhSd** [comment]
это тип сами сервера вккоина

**Comment by cbugerr** [comment]
Заработало после последней обновы

**Comment by SheyhSd** [comment]
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'open'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Desktop\коин\VCoinX-master\index.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Bot was forced to exit . . .
Для продолжения нажмите любую клавишу . . .



это че за ошибка?

**Comment by raywave** [comment]
плачь и танцуй с бубном
