### ISSUE TITLE
Linux ERROR

### ISSUE THREAD

**Issue by nol1cx** [cursedseal/VCoinX#126]
root@fizukplay:/var/www/vkcoin1# ./start.sh
> [07.04.2019 09:36:18]: VCoinX загружается...
[07.04.2019 09:36:19]: VCoinX загружен...
[07.04.2019 09:36:19]: Позиция в топе: 2148056  Количество коинов: 27 575,308
[07.04.2019 09:36:19]: Пользователь успешно загружен.
[07.04.2019 09:36:19]: Скорость: 19,000 коинов / тик.
VCoinX спонсируется сайтом lolzteam.net - форум об играх и читах, хак разделы, бруты и чекеры, способы заработка и раздачи баз.
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: spawn /var/www/vkcoin1/node_modules/open/xdg-open EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:253:12)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

**Comment by mulfyx** [comment]
в ```index.js``` замени ```open = require('open')``` на ```open = () => {}``` (заглушка на модуль)

**Comment by raywave** [comment]
решение выше
