### ISSUE TITLE
Ошибка вот, но токен вставил и NodeJS стоит

### ISSUE THREAD

**Issue by vladeslavek** [cursedseal/VCoinX#171]
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

NodeJS поставил 11 версии, но не через MSI-установщик (ошибка 2755, гугл не помог), а через архив.

PS. А еще install packages.bat не выводит все красиво в строку, а просто показывает меняющиеся / | \, однако вроде все завершается как надо

**Comment by raywave** [comment]
конфиг указывай корректно
