### ISSUE TITLE
Переподключение бота

### ISSUE THREAD

**Issue by Homosanians** [cursedseal/VCoinX#185]
> На стороне сервера возникла ошибка: Unexpected server response: 200

Сделайте переподключение к серверу после вывода этого сообщения ботом

**Comment by Homosanians** [comment]
Эта проблема с response: 200 массовая и далеко не только у меня

**Comment by Homosanians** [comment]
Та же ошибка на 1.3.6(542df85)

```
8|vk-3     | На стороне сервера возникла ошибка: Unexpected server response: 200
8|vk-3     | На стороне сервера возникла ошибка: Unexpected server response: 200
8|vk-3     | На стороне сервера возникла ошибка: Unexpected server response: 200
8|vk-3     | На стороне сервера возникла ошибка: Unexpected server response: 200
8|vk-3     | На стороне сервера возникла ошибка: Unexpected server response: 200
8|vk-3     | На стороне сервера возникла ошибка: Unexpected server response: 200
8|vk-3     | TypeError: Cannot read property '7540' of undefined
8|vk-3     |     at Timeout._onTimeout (/opt/VCoinX/VCoinWS.js:48:51)
8|vk-3     |     at ontimeout (timers.js:482:11)
8|vk-3     |     at tryOnTimeout (timers.js:317:5)
8|vk-3     |     at Timer.listOnTimeout (timers.js:277:5)
8|vk-3     | На стороне сервера возникла ошибка: [object Object]
8|vk-3     | На стороне сервера возникла ошибка: [object Object]
8|vk-3     | На стороне сервера возникла ошибка: [object Object]
8|vk-3     | На стороне сервера возникла ошибка: [object Object]
```
