### ISSUE TITLE
Ошибка при debug

### ISSUE THREAD

**Issue by JoshOOOOWAH** [cursedseal/VCoinX#193]
При использовании команды debug выходит сообщение

> updatesInterval 3000

, а за ним ошибка:
```
(node:6353) UnhandledPromiseRejectionWarning: ReferenceError: updatesLastTime is not defined
    at Interface.rl.on (/home/centos/miner/index.js:351:44)
    at Interface.emit (events.js:189:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._line (readline.js:638:8)
    at Interface._ttyWrite (readline.js:919:14)
    at ReadStream.onkeypress (readline.js:168:10)
    at ReadStream.emit (events.js:189:13)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1022:36)
(node:6353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by raywave** [comment]
забыл вырезать, в некст обнове фикс.

**Comment by TemaSM** [comment]
@cursedseal вырезал на своей ветке, сливаю
