### ISSUE TITLE
Не запускается - Cannot read property

### ISSUE THREAD

**Issue by JoshOOOOWAH** [cursedseal/VCoinX#214]
При попытке запуска бота через launch.sh или же node index.js вылезает подобная ошибка на версии 1.3.11
```
child_process.js:656
    throw err;
    ^

Error: Command failed: npm i --only=prod --no-audit --no-progress
npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/centos/.npm/_logs/2019-04-10T10_06_31_852Z-debug.log

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.<anonymous> (/home/centos/miner/index.js:5:44)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

```

**Comment by ghost** [comment]
ошибка pakages.json
