### ISSUE TITLE
Помогите с ошибкой

### ISSUE THREAD

**Issue by CODEHOOKED** [cursedseal/VCoinX#49]
[05.04.2019 12:01:30]: [ОШИБКА]: Пользователь отключен от сервера.
                Через 10 секунд будет выполнен перезапуск.

**Comment by NilonT** [comment]
+, у меня тоже

**Comment by NilonT** [comment]
[05.04.2019 15:41:04]: VCoinX загружается...
Unexpected server response: 500
[05.04.2019 15:41:05]: [ОШИБКА]: Пользователь отключен от сервера.
                Через 10 секунд будет выполнен перезапуск.

**Comment by HorJoy2** [comment]
Попробуйте вместо токена поставить ссылку
мне помогло

**Comment by CODEHOOKED** [comment]
Помог легаси.

**Comment by NilonT** [comment]
> Попробуйте вместо токена поставить ссылку
> мне помогло

Ссылку страницы в токен? или юрл

**Comment by HorJoy2** [comment]
в DONEURL

**Comment by VEXITYa** [comment]
> Помог легаси.

что?

**Comment by quelian** [comment]
> Помог легаси.

Что это? Можно ссылку?

**Comment by NilonT** [comment]
> в DONEURL

мне туда всю ссылку или только id?

**Comment by CODEHOOKED** [comment]
https://github.com/Inzilkin/VCoinXLEGACYOLD/releases

**Comment by quelian** [comment]
> https://github.com/Inzilkin/VCoinXLEGACYOLD/releases

Заработало. Спасибо)))

**Comment by NilonT** [comment]
> https://github.com/Inzilkin/VCoinXLEGACYOLD/releases

Error: Cannot find module 'vk-io'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Aktan\Desktop\VCoinXLEGACYOLD-release\index.js:4:9)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Bot was forced to exit . . .
Для продолжения нажмите любую клавишу . . .

**Comment by HorJoy2** [comment]
https://drive.google.com/open?id=1cGjBnehpI7VfmOuPFoTCmdb8_Zn81f_Z
вот эту ссылку вроде

**Comment by NilonT** [comment]
> https://github.com/Inzilkin/VCoinXLEGACYOLD/releases

А, всё, спасибо. Это я затупил:3

**Comment by raywave** [comment]
фикс 1.2.5

**Comment by NilonT** [comment]
> фикс 1.2.5

обновление вышло?
