### ISSUE TITLE
ПРоблема на LINUX

### ISSUE THREAD

**Issue by nol1cx** [cursedseal/VCoinX#57]
root@fizukplay:/var/www/VKCOIN1# nodejs index.js
/var/www/VKCOIN1/index.js:2
    {
    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

**Comment by realkarmakun** [comment]
В конфиге токен неправильно указан. У тебя там кобка фигурная съехала наверное или типо того

**Comment by nol1cx** [comment]
> В конфиге токен неправильно указан. У тебя там кобка фигурная съехала наверное или типо того

Не, все верно

**Comment by raywave** [comment]
хз, если найдешь причину - отпиши сюда. пока закрою.

**Comment by nol1cx** [comment]
> хз, если найдешь причину - отпиши сюда. пока закрою.

Нужно было апгрейднуть node js на машине, несмотря на то, что установил последнюю. Так и живем))
