### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by YardalGedal** [cursedseal/VCoinX#75]
При запуске получаю следующую проблему:
`ReferenceError: window is not defined
    at eval (eval at ws.onmessage (/home/user/VCoinX/VCoinWS.js:123:41), <anonymous>:1:37)
    at WebSocket.ws.onmessage (/home/user/VCoinX/VCoinWS.js:123:41)
    at WebSocket.onMessage (/home/user/VCoinX/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (/home/user/VCoinX/node_modules/ws/lib/websocket.js:789:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (/home/user/VCoinX/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/home/user/VCoinX/node_modules/ws/lib/receiver.js:352:17)
`

**Comment by raywave** [comment]
Данный баг на легаси? Проходит само, позже мб пофикшу.
