### ISSUE TITLE
Ошибка при запуске бота "ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by mrAsh4r** [cursedseal/VCoinX#78]
Лог работы:
> [06.04.2019 08:10:16]: VCoinX загружается...
[06.04.2019 08:10:19]: VCoinX загружен...
[06.04.2019 08:10:19]: Позиция в топе: 532672   Количество коинов: 248 390,571
[06.04.2019 08:10:19]: Пользователь успешно загружен.
[06.04.2019 08:10:19]: Скорость: 26,461 коинов / тик.
ReferenceError: window is not defined
    at eval (eval at ws.onmessage (C:\Users\Sil3nce\Desktop\VCoinX-master\VCoinWS.js:123:41), <anonymous>:1:34)
    at WebSocket.ws.onmessage (C:\Users\Sil3nce\Desktop\VCoinX-master\VCoinWS.js:123:41)
    at WebSocket.onMessage (C:\Users\Sil3nce\Desktop\VCoinX-master\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (C:\Users\Sil3nce\Desktop\VCoinX-master\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:189:13)
    at Receiver.dataMessage (C:\Users\Sil3nce\Desktop\VCoinX-master\node_modules\ws\lib\receiver.js:422:14)
    at Receiver.getData (C:\Users\Sil3nce\Desktop\VCoinX-master\node_modules\ws\lib\receiver.js:352:17)
    at Receiver.startLoop (C:\Users\Sil3nce\Desktop\VCoinX-master\node_modules\ws\lib\receiver.js:138:22)
    at Receiver._write (C:\Users\Sil3nce\Desktop\VCoinX-master\node_modules\ws\lib\receiver.js:74:10)
[06.04.2019 08:10:21]: [ОШИБКА]: Обнаружен brokenEvent, видимо сервер сломался.
                Через 10 секунд будет выполнен перезапуск.

После нескольких попыток скрипту перезапуститься он пытается сменить сервер: 
>[06.04.2019 08:11:30]: [ОШИБКА]: Обнаружен brokenEvent, видимо сервер сломался.
                Через 10 секунд будет выполнен перезапуск.
[06.04.2019 08:11:30]: [ОШИБКА]: Достигнут лимит попыток подключиться к серверу.
                        Производится смена сервера...

**Comment by raywave** [comment]
По идее фикс в 1.2.5
